// styles.ts —— App 共用 StyleSheet（由 App.tsx 抽出，只依賴 theme）
import { StyleSheet } from "react-native";
import { type Theme } from "./theme";

// 圓體字型:全 app 內文用 jf 粉圓(全繁);數字/英文用 Baloo 2（由 useFonts 載,名 Huninn/Baloo2）
export const FONT_BODY = 'Huninn';
export const FONT_NUM = 'Baloo2';
// 自動把 fontFamily 套入所有「文字」style(有 fontSize 或 color),免逐個改;style 自帶 fontFamily 可覆蓋
function applyFont(o: Record<string, any>): Record<string, any> {
  const r: Record<string, any> = {};
  for (const k in o) {
    const st = o[k];
    r[k] = st && (st.fontSize != null || st.color != null) ? { fontFamily: FONT_BODY, ...st } : st;
  }
  return r;
}

// 由主題 token 砌 StyleSheet（每個風格各自 memo 一份,見 ui-theme.tsx）
export function makeStyles(C: Theme) {
  const GLOW = C.glow;
  const raw: Record<string, any> = {
  root: { flex: 1, flexDirection: 'row', backgroundColor: C.bg },
  rootPort: { flex: 1, backgroundColor: C.bg },

  focused: { borderColor: C.cyan, borderWidth: 2 },
  rowFocused: { backgroundColor: C.focusBg },

  // ===== Header / brand =====
  glyph: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: C.cyan,
    backgroundColor: C.surface,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  glyphImg: { width: 34, height: 34 },
  glyphText: { color: '#fff', fontSize: 15, fontWeight: '900', letterSpacing: 0.5 },
  glyphMini: { width: 30, height: 30, borderRadius: 9, backgroundColor: C.rose, alignItems: 'center', justifyContent: 'center', marginBottom: 10 },
  glyphMiniText: { color: '#fff', fontSize: 12, fontWeight: '900' },
  glyphMiniImg: { width: 32, height: 32, borderRadius: 16, marginBottom: 10 },
  brandRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 12 },
  collapseBtn: {
    width: 28,
    height: 28,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.line2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  collapseIcon: { color: C.muted, fontSize: 14, fontWeight: '800' },

  // site pulldown
  sitePd: { flex: 1, minWidth: 0 },
  spCur: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: C.bg,
    borderWidth: 1,
    borderColor: C.line2,
    borderRadius: 9,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  spCurOpen: { borderColor: C.curOpenBorder },
  spBrand: { borderColor: C.brandBorder },
  spDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: C.cyan, shadowColor: C.cyan, shadowRadius: 6, shadowOpacity: 1 },
  spName: { color: C.text, fontSize: 13, fontWeight: '800', flex: 1 },
  spCar: { color: C.muted, fontSize: 11 },
  spMenu: { backgroundColor: C.surface, borderWidth: 1, borderColor: C.line2, borderRadius: 12, padding: 6, width: 220, maxHeight: 360 },
  spMenuLand: { position: 'absolute', top: 64, left: 60 },
  spMenuPort: { position: 'absolute', top: 64, left: 56 },
  spOpt: { flexDirection: 'row', alignItems: 'center', gap: 9, paddingHorizontal: 10, paddingVertical: 9, borderRadius: 8 },
  spOptOn: { backgroundColor: C.rose },
  spOptText: { color: C.muted, fontSize: 13, fontWeight: '700' },
  spOptTextOn: { color: '#fff' },
  spOptCk: { color: '#fff', marginLeft: 'auto', fontSize: 12 },

  // ===== Sidebar =====
  sidebar: { width: 290, backgroundColor: C.surface, borderRightWidth: 1, borderRightColor: C.line },
  sbTop: { padding: 14, paddingBottom: 6 },
  search: {
    backgroundColor: C.bg,
    borderColor: C.line2,
    borderWidth: 1,
    borderRadius: 11,
    paddingHorizontal: 12,
    paddingVertical: 0,
    height: 40,
    color: C.text,
    fontSize: 13,
    marginBottom: 8,
  },
  railBar: { width: 44, backgroundColor: C.surface, borderRightWidth: 1, borderRightColor: C.line, alignItems: 'center', paddingTop: 16 },
  railIcon: { color: C.cyan, fontSize: 20, fontWeight: '800' },

  // year header
  yrHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: C.surface, paddingHorizontal: 14, paddingVertical: 6 },
  yrLabel: { color: C.cyan, fontSize: 12, fontWeight: '800' },
  yrLine: { flex: 1, height: 1, backgroundColor: C.line },
  yrCount: { color: C.mutedDim, fontSize: 11, fontWeight: '700' },

  // anime row (text-only, dense)
  row: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, marginHorizontal: 6, borderRadius: 10 },
  rowActive: { backgroundColor: C.activeBg, borderWidth: 1, borderColor: C.activeBorder },
  rowMain: { flex: 1, paddingVertical: 7, paddingHorizontal: 4, borderRadius: 8 },
  rowName: { color: C.text, fontSize: 14, fontWeight: '700' },
  rowNameActive: { color: C.cyan },
  rowMeta: { color: C.muted, fontSize: 11, marginTop: 1 },
  rowSite: { color: C.cyan, fontWeight: '800' },
  rowLive: { color: C.good, fontStyle: 'italic' },
  // 同名分組:每個來源一粒可撳 chip（單行橫向拖動,唔換行）
  rowSrcRow: { marginTop: 4 },
  rowSrcRowContent: { flexDirection: 'row', alignItems: 'center', paddingRight: 8 },
  rowSrcChip: { paddingHorizontal: 7, paddingVertical: 3, borderRadius: 6, borderWidth: 1, borderColor: C.line2, backgroundColor: C.surface, marginRight: 6 },
  rowSrcChipOn: { borderColor: C.chipOnBorder, backgroundColor: C.chipOnBg },
  rowSrcText: { color: C.muted, fontSize: 11 },
  rowSrcTextOn: { color: C.cyan, fontWeight: '700' },
  heart: { paddingHorizontal: 8, paddingVertical: 6 },
  heartIcon: { color: C.mutedDim, fontSize: 16, fontWeight: '700' },
  heartOn: { color: C.rose },
  empty: { color: C.muted, textAlign: 'center', marginTop: 28 },
  err: { color: C.errText, padding: 8, fontSize: 12 },

  // ===== Player column =====
  playerCol: { flex: 1, padding: 12, gap: 8 },
  playerArea: { flex: 1, borderRadius: 18, overflow: 'hidden', backgroundColor: C.ink },
  playerAreaPortrait: { flex: 0, aspectRatio: 16 / 9, marginHorizontal: 10, marginTop: 8 },
  video: { flex: 1, backgroundColor: '#000' },
  placeholder: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: C.surface },
  placeholderText: { color: C.muted, fontSize: 15 },

  // title bar
  titleBar: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 10, paddingVertical: 6, flexWrap: 'wrap' },
  tbName: { color: C.text, fontSize: 16, fontWeight: '800', flexShrink: 1 },
  tbEp: { backgroundColor: C.raised, borderRadius: 7, paddingHorizontal: 8, paddingVertical: 3 },
  tbEpText: { color: C.text, fontSize: 12, fontWeight: '700' },
  tbResume: { borderWidth: 1, borderColor: C.resumeBorder, borderRadius: 7, paddingHorizontal: 8, paddingVertical: 3 },
  tbResumeText: { color: C.cyan, fontSize: 12, fontWeight: '700' },
  favFilter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 40,
    gap: 6,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: C.line2,
    backgroundColor: C.bg,
  },
  favFilterOn: { backgroundColor: C.loveBg, borderColor: C.rose },
  favFilterText: { color: C.muted, fontSize: 12, fontWeight: '700' },
  panelToggle: { height: 36, justifyContent: 'center', paddingHorizontal: 11, borderRadius: 10, borderWidth: 1, borderColor: C.line2, backgroundColor: C.bg },
  panelToggleText: { color: C.cyan, fontSize: 12, fontWeight: '800' },
  favFilterTextOn: { color: C.rose },
  collectBtn: { height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 10, paddingHorizontal: 13, backgroundColor: C.raised },
  collectBtnOn: { backgroundColor: C.rose },
  collectText: { color: C.muted, fontSize: 12, fontWeight: '800' },
  collectTextOn: { color: '#fff' },

  // ===== Right rail (episodes) =====
  rightRail: { width: 210, backgroundColor: C.surface, borderLeftWidth: 1, borderLeftColor: C.line, padding: 14, gap: 10 },
  pickerHead: { flexDirection: 'row', alignItems: 'baseline' },
  pickerTitle: { color: C.text, fontSize: 15, fontWeight: '800' },
  pickerCount: { color: C.muted, fontSize: 12, fontWeight: '600' },
  rangeRow: { maxHeight: 36, flexGrow: 0 },
  range: { backgroundColor: C.bg, borderWidth: 1, borderColor: C.line2, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8, marginRight: 6 },
  rangeOn: { backgroundColor: C.rose, borderColor: C.rose },
  rangeText: { color: C.muted, fontSize: 12, fontWeight: '800' },
  rangeTextOn: { color: '#fff' },
  epScroll: { flex: 1 },
  epScrollPort: { maxHeight: 110, marginBottom: 4 }, // 3 行（30×3 + 6×2 + 8 padding）封頂，多過內部捲
  lockedControls: { backgroundColor: C.bg }, // 揀咗動畫時固定喺頂嘅控制區（唔跟清單捲）
  epWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, paddingBottom: 8 },
  ep: { height: 30, borderRadius: 8, backgroundColor: C.raised, borderWidth: 1, borderColor: C.line, alignItems: 'center', justifyContent: 'center' },
  epOn: { backgroundColor: C.rose, borderColor: C.rose },
  epText: { color: C.text, fontSize: 13, fontWeight: '800', fontFamily: FONT_NUM },
  epTextOn: { color: '#fff' },

  // settings row (來源)
  settingsRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  searchFavRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 12, marginBottom: 8, marginHorizontal: 10 },
  searchFlex: { flex: 1, marginBottom: 0 },
  pairRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  srcBar: {
    flexShrink: 1,
    flexDirection: 'row',
    alignItems: 'center',
    height: 36,
    gap: 6,
    backgroundColor: C.bg,
    borderWidth: 1,
    borderColor: C.line2,
    borderRadius: 9,
    paddingHorizontal: 9,
  },
  srcBarOff: { opacity: 0.45 }, // 單一來源:灰咗、唔可撳
  srcBars: { color: C.cyan, fontSize: 10, letterSpacing: -1 },
  srcName: { color: C.text, fontSize: 12, fontWeight: '800', flexShrink: 1 },
  srcMs: { color: C.cyan, fontSize: 11, fontWeight: '700' },
  srcOk: { color: C.good, fontSize: 11 },
  srcCaret: { color: C.muted, fontSize: 11, marginLeft: 'auto' },

  railActions: { gap: 8 },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: C.bg,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  toggleLabel: { color: C.text, fontSize: 12, fontWeight: '700' },
  switch: { width: 40, height: 22, borderRadius: 11, backgroundColor: C.raised2, padding: 2, justifyContent: 'center' },
  switchOn: { backgroundColor: C.rose },
  knob: { width: 18, height: 18, borderRadius: 9, backgroundColor: '#fff', alignSelf: 'flex-start' },
  knobOn: { alignSelf: 'flex-end' },
  btnFull: { borderRadius: 12, paddingVertical: 12, alignItems: 'center', backgroundColor: C.rose },
  btnFullText: { color: '#fff', fontSize: 14, fontWeight: '900' },

  divider: { height: 1, backgroundColor: C.line, marginVertical: 10, marginHorizontal: 10 },

  // ===== overlays / menus =====
  overlayBackdrop: {
    position: 'absolute',
    top: -22,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 200,
    elevation: 200,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  // 頂部對齊(⚙ 設定用):切換分頁內容高度變都唔會上下跳
  overlayTop: { justifyContent: 'flex-start', paddingTop: 96 },
  srcMenu: { width: 248, maxHeight: '70%', backgroundColor: C.surface, borderWidth: 1, borderColor: C.line2, borderRadius: 13, padding: 8 },
  srcMenuTitle: { color: C.muted, fontSize: 11, fontWeight: '800', marginBottom: 6, paddingHorizontal: 4 },
  spSection: { color: C.cyan, fontSize: 10, fontWeight: '800', marginTop: 8, marginBottom: 4, paddingHorizontal: 4, letterSpacing: 0.5 },
  spVer: { color: C.mutedDim, fontSize: 10, marginTop: 4, paddingHorizontal: 4, lineHeight: 14 },
  spNameField: { marginTop: 6, backgroundColor: C.raised, borderRadius: 8 },
  spNameInput: { paddingHorizontal: 12, paddingVertical: 8, color: C.text, fontSize: 13 },
  srcItem: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 10, paddingVertical: 9, borderRadius: 8, marginBottom: 4, borderWidth: 2, borderColor: 'transparent' },
  srcItemOn: { backgroundColor: C.activeBg },
  srcItemHi: { borderColor: C.cyan },
  srcItemText: { color: C.text, fontSize: 13, fontWeight: '700' },
  srcItemTextOn: { color: C.cyan },
  srcItemMs: { color: C.cyan, fontSize: 11, fontWeight: '800' },
  srcItemCk: { color: C.good, fontSize: 12, marginLeft: 6 },
  srcNote: { color: C.mutedDim, fontSize: 10, marginTop: 6, paddingHorizontal: 4 },

  // ===== 雲端同步 =====
  cloudBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 36,
    maxWidth: 120,
    paddingHorizontal: 10,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: C.line2,
    backgroundColor: C.bg,
  },
  cloudBtnOn: { borderColor: 'rgba(91,230,168,0.5)', backgroundColor: 'rgba(91,230,168,0.12)' },
  cloudText: { color: C.muted, fontSize: 12, fontWeight: '800' },
  cloudTextOn: { color: C.good },
  syncCard: {
    width: 320,
    maxWidth: '90%',
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.line2,
    borderRadius: 16,
    padding: 18,
    gap: 10,
  },
  syncTitle: { color: C.text, fontSize: 18, fontWeight: '900' },
  syncSub: { color: C.muted, fontSize: 12, lineHeight: 17, marginBottom: 4 },
  otaNotes: { backgroundColor: 'rgba(255,255,255,0.05)', borderWidth: 1, borderColor: C.line2, borderRadius: 10, padding: 10, gap: 4 },
  otaNotesLabel: { color: C.text, fontSize: 12, fontWeight: '800' },
  otaNotesText: { color: C.muted, fontSize: 13, lineHeight: 19 },
  syncWho: { color: C.good, fontSize: 14, fontWeight: '800', marginBottom: 4 },
  syncInput: {
    backgroundColor: C.bg,
    borderWidth: 1,
    borderColor: C.line2,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: C.text,
    fontSize: 14,
  },
  syncErr: { color: C.errText, fontSize: 12 },
  syncRow: { flexDirection: 'row', gap: 10, marginTop: 4 },
  syncBtn: { backgroundColor: C.rose, borderRadius: 11, paddingVertical: 12, alignItems: 'center' },
  syncBtnText: { color: '#fff', fontSize: 14, fontWeight: '900' },
  syncBtnGhost: {
    borderRadius: 11,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: C.line2,
    backgroundColor: C.bg,
  },
  syncBtnGhostText: { color: C.text, fontSize: 14, fontWeight: '800' },
  syncLogout: { position: 'absolute', top: 8, right: 10, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8 },
  syncLogoutText: { color: C.muted, fontSize: 12, fontWeight: '700' },

  // ===== Portrait =====
  appbar: { flexDirection: 'row', alignItems: 'center', gap: 9, paddingHorizontal: 12, paddingVertical: 8 },
  brandWord: { color: C.text, fontSize: 16, fontWeight: '900', letterSpacing: 0.3, flexShrink: 1 },
  iconBtn: { height: 36, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 11, borderRadius: 9, borderWidth: 1, borderColor: C.line2, backgroundColor: C.bg },
  iconBtnText: { color: C.muted, fontSize: 15, fontWeight: '800' },
  portCtrlRow: { flexDirection: 'row', alignItems: 'center', height: 34, gap: 8, paddingHorizontal: 10, marginVertical: 6 },
  ctrlTitleWrap: { flex: 1, flexDirection: 'row', alignItems: 'baseline', overflow: 'hidden' },
  ctrlTitle: { color: C.text, fontSize: 15, fontWeight: '800' },
  ctrlCount: { color: C.muted, fontSize: 12, fontWeight: '600' },

  // ===== PlayerOverlay =====
  tapCatcher: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0 },
  ctrCenter: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 28 },
  ctrBtn: { alignItems: 'center', justifyContent: 'center', paddingHorizontal: 8 },
  ctrIcon: { color: '#fff', fontSize: 30, fontWeight: '800' },
  ctrIconSm: { color: '#fff', fontSize: 11, fontWeight: '800', marginTop: -6 },
  ctrPlay: { width: 64, height: 64, borderRadius: 32, backgroundColor: 'rgba(255,255,255,0.95)', alignItems: 'center', justifyContent: 'center' },
  ctrPlayIcon: { color: C.ink, fontSize: 24, fontWeight: '900' },
  ovBtn: { position: 'absolute', top: '50%', marginTop: -36, width: 46, height: 72, borderRadius: 12, backgroundColor: 'rgba(11,14,26,0.55)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.18)', alignItems: 'center', justifyContent: 'center' },
  ovLeft: { left: 10 },
  ovRight: { right: 10 },
  ovOff: { opacity: 0.25 },
  ovText: { color: '#fff', fontSize: 14, fontWeight: '800', textAlign: 'center', lineHeight: 18 },
  fsTopBar: { position: 'absolute', top: 44, left: 0, right: 0, alignItems: 'center' },
  inlineTop: { position: 'absolute', top: 10, left: 12, right: 60, zIndex: 5 },
  inlineTopName: { color: '#fff', fontSize: 15, fontWeight: '800', textShadowColor: 'rgba(0,0,0,0.7)', textShadowRadius: 5 },
  inlineTopEp: { color: 'rgba(255,255,255,0.85)', fontSize: 12, fontWeight: '700', marginTop: 2, textShadowColor: 'rgba(0,0,0,0.7)', textShadowRadius: 5 },
  fsTopName: { color: '#fff', fontSize: 51, fontWeight: '800', maxWidth: '70%', textShadowColor: 'rgba(0,0,0,0.6)', textShadowRadius: 6 },
  fsTopEp: { color: 'rgba(255,255,255,0.75)', fontSize: 39, fontWeight: '700', marginTop: 6, textShadowColor: 'rgba(0,0,0,0.6)', textShadowRadius: 6 },
  fsToggle: { position: 'absolute', top: 10, right: 10, backgroundColor: 'rgba(11,14,26,0.55)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.18)', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 5 },
  fsToggleFs: { top: 40, right: 30, backgroundColor: C.loveSolid, borderColor: '#fff', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 10 },
  fsToggleText: { color: '#fff', fontSize: 13, fontWeight: '800' },
  // 開頭／結尾 標記掣（進度條上方，左／右分佈）
  markRow: { position: 'absolute', left: 14, right: 14, bottom: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  markGroup: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  markBtn: { backgroundColor: 'rgba(11,14,26,0.6)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 7 },
  markBtnText: { color: '#fff', fontSize: 13, fontWeight: '800' },
  markClear: { width: 28, height: 28, borderRadius: 8, backgroundColor: C.loveBtn, alignItems: 'center', justifyContent: 'center' },
  markClearText: { color: '#fff', fontSize: 13, fontWeight: '900' },
  seekRow: { position: 'absolute', left: 14, right: 14, bottom: 12, flexDirection: 'row', alignItems: 'center', gap: 10 },
  timeText: { color: '#fff', fontSize: 12, fontWeight: '700', minWidth: 92, fontFamily: FONT_NUM },
  seekBarWrap: { flex: 1, height: 22, justifyContent: 'center' },
  seekTrack: { height: 4, borderRadius: 2, backgroundColor: 'rgba(255,255,255,0.32)' },
  seekFill: { position: 'absolute', left: 0, height: 4, borderRadius: 2, backgroundColor: GLOW },
  seekKnob: { position: 'absolute', width: 16, height: 16, borderRadius: 8, backgroundColor: '#fff', top: 3 },
  // 角色 toggle + 遙控器面板
  roleSeg: { flexDirection: 'row', height: 36, borderWidth: 1, borderColor: C.line2, borderRadius: 8, overflow: 'hidden', marginRight: 8 },
  roleSegBtn: { paddingHorizontal: 10, justifyContent: 'center' },
  roleSegOn: { backgroundColor: C.roleSegOnBg },
  roleSegText: { color: C.muted, fontSize: 12, fontWeight: '800' },
  roleSegTextOn: { color: C.cyan },

  // ⚙ 設定分頁（播放設定 | 外觀主題）
  setTabs: { flexDirection: 'row', gap: 8, marginTop: 6, marginBottom: 4 },
  setTab: { flex: 1, height: 34, borderRadius: 9, borderWidth: 1, borderColor: C.line2, backgroundColor: C.bg, alignItems: 'center', justifyContent: 'center' },
  setTabOn: { backgroundColor: C.chipOnBg, borderColor: C.chipOnBorder },
  setTabText: { color: C.muted, fontSize: 13, fontWeight: '800' },
  setTabTextOn: { color: C.cyan },
  remotePanel: { backgroundColor: C.surface, borderRadius: 18, marginHorizontal: 10, marginTop: 8, padding: 14, gap: 8 },
  remoteHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  remoteTag: { color: C.text, fontSize: 14, fontWeight: '900' },
  remoteCenter: { alignItems: 'center', gap: 10, paddingVertical: 28 },
  remoteHint: { color: C.text, fontSize: 15, fontWeight: '800' },
  remoteSub: { color: C.muted, fontSize: 12, textAlign: 'center', lineHeight: 18 },
  rcTopRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  rcTarget: { backgroundColor: C.raised, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6, maxWidth: 130 },
  rcTargetText: { color: C.text, fontSize: 12, fontWeight: '700' },
  rcTargetStatic: { color: C.muted, fontSize: 12, fontWeight: '700', maxWidth: 130 },
  rcNow: { flex: 1, color: C.text, fontSize: 14, fontWeight: '800', textAlign: 'center' },
  rcFsBtn: { backgroundColor: C.raised, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6 },
  rcFsText: { color: C.cyan, fontSize: 12, fontWeight: '800' },
  rcSeekRow: { paddingVertical: 8 },
  rcSeekWrap: { height: 18, justifyContent: 'center' },
  rcTime: { color: C.muted, fontSize: 12 },
  rcRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 14, marginTop: 4 },
  rcPlay: { transform: [{ scale: 1.2 }] },
  rcBtnIcon: { color: C.text, fontSize: 28 },
  rcBtnOff: { color: C.mutedDim },
  rcBtnSm: { color: C.text, fontSize: 15, fontWeight: '700' },
  rcMarkRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8 },
  rcMarkGroup: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  rcMarkBtn: { backgroundColor: C.raised, borderRadius: 8, paddingHorizontal: 14, paddingVertical: 8 },
  rcClearBtn: { backgroundColor: C.raised, borderRadius: 8, width: 34, height: 34, alignItems: 'center', justifyContent: 'center' },
  rcClearText: { color: C.muted, fontSize: 14, fontWeight: '800' },
  rcMarkText: { color: C.text, fontSize: 13, fontWeight: '700' },
  rcLockBtn: { backgroundColor: C.raised, borderRadius: 8, paddingHorizontal: 14, paddingVertical: 8, alignItems: 'center', justifyContent: 'center' },
  rcLockOn: { backgroundColor: C.cyan },
  rcLockText: { color: C.muted, fontSize: 16, fontWeight: '800' },
  rcLockTextOn: { color: C.bg },
  rcLockHint: { color: C.cyan, fontSize: 12, fontWeight: '700', textAlign: 'center', marginTop: 6 },

  adSkipNote: { position: 'absolute', top: 14, alignSelf: 'center', backgroundColor: 'rgba(11,14,26,0.8)', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 6 },
  adSkipText: { color: '#fff', fontSize: 12, fontWeight: '700' },

  // fullscreen overlay
  fsContainer: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: '#000', zIndex: 100, elevation: 100 },
  };
  return StyleSheet.create(applyFont(raw));
}
